### ISSUE TITLE
Final to-do list.

### ISSUE THREAD

**Issue by JonasMoss** [JonasMoss/p-hacking#1]
- [x] Proposition 2: Rewrite to keep it inside the bounds of the document.
- [x] Check if the appendix says everything it should.
- [x] Reread simulation part.
- [x] Add info about N in the simulation; make explicit reference to STAN. Say have many chains have been used. Add link to OSF repo.
- [x] Check paper for too tall lines.
- [x] Remove excessive \emph.
- [x] Fix cases.
- [x] Use `\enquote` for citations.
- [x] Check use of `\left(` etc.
- [x] Reduce adjective heaviness.
- [x] Remove excessive parenthetical remarks.
- [x] Check Example section.
- [x] "Note that", "note the", "given by", etc.
- [x] Read through one last time.
