### ISSUE TITLE
Todo-list.

### ISSUE THREAD

**Issue by JonasMoss** [JonasMoss/p-hacking#5]
## General
- [ ] Italicized p-value(s), p-hack, p-hacking.
- [ ] Consistently capitalize Section instead of section.
- [ ] Consistently "make inference", not "do inference"
- [ ] Consistently used "cutoff" instead of "cut-off".
- [ ] Checked if all equation labels are used.

## 1. Introduction
- [ ] Changed reference to Iyengar and Greenhouse to the classical R Rosenthal
- [ ] Well known to well-known.
- [ ] "... to deal with publication bias are [the] selection models"
- [ ] Other examples of selection
models include those of Dear and Begg (1992) and Copas and Shi (2000). (See bla bla for a review.)
- [ ] Add a little more copas.
- [ ] "the models PET and PET-PEESE" -> "PET and PET-PEESE"
- [ ] "For more information on publication bias
and a good review of large part of these methods we refer to the book by" ->
" For more information on publication bias we refer to the book by"
- [ ] well captured -> captured well
- [ ] Removed (Carter et al., 2019) as justification of p-value-based 
- [ ] "real data examples" -> "examples"
- [ ] "We conclude with some remarks in Section 5." -> "We conclude in Section 5".

### 2.1 Framework
- [ ] "It has instead been transformed into something else by
the forces of publication bias and p-hacking." -> "It has been transformed into something else by
the forces of publication bias and p-hacking."
- [ ] "The publication bias model" -> "The selection function publication bias model"
- [ ] "model are models that transform" -> "transform".

### 2.2 The selection model
- [ ] "selection mechanism can be changed by conditioning on \theta_i in the denominator".
- [ ] "This is not the case for the publication bias model." -> " "

### 2.3 The publication bias model
- [ ] "It seems therefore useful to add an additional
splitting point at 0:025" -> "Therefore it is useful to add..."
- [ ] "(this possibility is already implemented in the R package associated with this
paper, publipha, see Moss, 2020, for more details)." -> removed parentheses.

### 2.4 The p-hacking model
- [ ] "the p-hacking scenario [,] \alpha is drawn from \omega"
- [ ] "and might depend on dovariates" should be its own sentence.
- [ ] "(that is, on the form of (1))", removed parentheses.
- [ ] "in general" -> ""
- [ ] "but the model below is presented in broad generality (J cut-offs)." -> removed parentheses

## 2.5 The difference between the models
- [ ] "while there is no closed form for the density" -> "but" instead of "while".
- [ ] "given the sampled" removed italics.
- [ ] "or" -> "that is, "
